// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow, TaggedUnion};

#[allow(unused_imports, dead_code)]
pub mod rust_namer_test {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow, TaggedUnion};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FIELD_UNION: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FIELD_UNION: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FIELD_UNION: [FieldUnion; 2] = [
  FieldUnion::NONE,
  FieldUnion::f,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FieldUnion(pub u8);
#[allow(non_upper_case_globals)]
impl FieldUnion {
  pub const NONE: Self = Self(0);
  pub const f: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::f,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::f => Some("f"),
      _ => None,
    }
  }

  #[inline]
  pub fn tag_as_f(
    o: flatbuffers::WIPOffset<FieldTable>,
  ) -> flatbuffers::UnionWIPOffset<FieldUnionUnionValue> {
    flatbuffers::UnionWIPOffset::new(Self::f, flatbuffers::WIPOffset::new(o.value()))
  }

}
impl core::fmt::Debug for FieldUnion {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for FieldUnion {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<u8, B>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for FieldUnion {
    type Output = FieldUnion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for FieldUnion {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for FieldUnion {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for FieldUnion {}

impl From<FieldUnion> for u8 {
  #[inline]
  fn from(v: FieldUnion) -> u8 {
    v.0
  }
}

impl<'a: 'b, 'b> flatbuffers::BuildVector<'a, 'b> for FieldUnion {
  type VectorBuilder = FieldUnionVectorBuilder<'a, 'b>;
}

pub struct FieldUnionVectorBuilder<'a: 'b, 'b> {
  fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  num_items: usize,
}

impl<'a: 'b, 'b> FieldUnionVectorBuilder<'a, 'b> {
  #[inline]
  pub fn new(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, num_items: usize) -> Self {
    fbb.start_union_vector::<FieldUnionUnionValue>(num_items);
    Self { fbb, num_items }
  }

  #[inline]
  pub fn finish(&mut self) -> flatbuffers::UnionVectorWIPOffsets<'a, FieldUnionUnionValue> {
    self.fbb.end_union_vector(self.num_items)
  }

  #[inline]
  pub fn push_as_f(&mut self, o: flatbuffers::WIPOffset<FieldTable>) {
    self.fbb.push_union_vector_item(FieldUnion::tag_as_f(o));
  }

}

pub struct FieldUnionUnionValue {}

impl flatbuffers::TaggedUnion for FieldUnionUnionValue {
  type Tag = FieldUnion;
}

impl<'a> flatbuffers::UnionVerifiable<'a> for FieldUnionUnionValue {
  fn run_union_verifier(
    v: &mut flatbuffers::Verifier,
    tag: <<Self as flatbuffers::TaggedUnion>::Tag as flatbuffers::Follow<'a>>::Inner,
    pos: usize,
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    match tag {
      FieldUnion::f => v
        .verify_union_variant::<flatbuffers::ForwardsUOffset<FieldTable>>(
          "FieldUnion::f",
          pos,
        ),
      _ => Ok(()),
    }
  }
}

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_GAME_MESSAGE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_GAME_MESSAGE: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_GAME_MESSAGE: [GameMessage; 4] = [
  GameMessage::NONE,
  GameMessage::PlayerStatEvent,
  GameMessage::PlayerSpectate,
  GameMessage::PlayerInputChange,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct GameMessage(pub u8);
#[allow(non_upper_case_globals)]
impl GameMessage {
  pub const NONE: Self = Self(0);
  pub const PlayerStatEvent: Self = Self(1);
  pub const PlayerSpectate: Self = Self(2);
  pub const PlayerInputChange: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::PlayerStatEvent,
    Self::PlayerSpectate,
    Self::PlayerInputChange,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::PlayerStatEvent => Some("PlayerStatEvent"),
      Self::PlayerSpectate => Some("PlayerSpectate"),
      Self::PlayerInputChange => Some("PlayerInputChange"),
      _ => None,
    }
  }

  #[inline]
  pub fn tag_as_player_stat_event(
    o: flatbuffers::WIPOffset<PlayerStatEvent>,
  ) -> flatbuffers::UnionWIPOffset<GameMessageUnionValue> {
    flatbuffers::UnionWIPOffset::new(Self::PlayerStatEvent, flatbuffers::WIPOffset::new(o.value()))
  }

  #[inline]
  pub fn tag_as_player_spectate(
    o: flatbuffers::WIPOffset<PlayerSpectate>,
  ) -> flatbuffers::UnionWIPOffset<GameMessageUnionValue> {
    flatbuffers::UnionWIPOffset::new(Self::PlayerSpectate, flatbuffers::WIPOffset::new(o.value()))
  }

  #[inline]
  pub fn tag_as_player_input_change(
    o: flatbuffers::WIPOffset<PlayerInputChange>,
  ) -> flatbuffers::UnionWIPOffset<GameMessageUnionValue> {
    flatbuffers::UnionWIPOffset::new(Self::PlayerInputChange, flatbuffers::WIPOffset::new(o.value()))
  }

}
impl core::fmt::Debug for GameMessage {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for GameMessage {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<u8, B>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for GameMessage {
    type Output = GameMessage;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for GameMessage {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for GameMessage {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for GameMessage {}

impl From<GameMessage> for u8 {
  #[inline]
  fn from(v: GameMessage) -> u8 {
    v.0
  }
}

impl<'a: 'b, 'b> flatbuffers::BuildVector<'a, 'b> for GameMessage {
  type VectorBuilder = GameMessageVectorBuilder<'a, 'b>;
}

pub struct GameMessageVectorBuilder<'a: 'b, 'b> {
  fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  num_items: usize,
}

impl<'a: 'b, 'b> GameMessageVectorBuilder<'a, 'b> {
  #[inline]
  pub fn new(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, num_items: usize) -> Self {
    fbb.start_union_vector::<GameMessageUnionValue>(num_items);
    Self { fbb, num_items }
  }

  #[inline]
  pub fn finish(&mut self) -> flatbuffers::UnionVectorWIPOffsets<'a, GameMessageUnionValue> {
    self.fbb.end_union_vector(self.num_items)
  }

  #[inline]
  pub fn push_as_player_stat_event(&mut self, o: flatbuffers::WIPOffset<PlayerStatEvent>) {
    self.fbb.push_union_vector_item(GameMessage::tag_as_player_stat_event(o));
  }

  #[inline]
  pub fn push_as_player_spectate(&mut self, o: flatbuffers::WIPOffset<PlayerSpectate>) {
    self.fbb.push_union_vector_item(GameMessage::tag_as_player_spectate(o));
  }

  #[inline]
  pub fn push_as_player_input_change(&mut self, o: flatbuffers::WIPOffset<PlayerInputChange>) {
    self.fbb.push_union_vector_item(GameMessage::tag_as_player_input_change(o));
  }

}

pub struct GameMessageUnionValue {}

impl flatbuffers::TaggedUnion for GameMessageUnionValue {
  type Tag = GameMessage;
}

impl<'a> flatbuffers::UnionVerifiable<'a> for GameMessageUnionValue {
  fn run_union_verifier(
    v: &mut flatbuffers::Verifier,
    tag: <<Self as flatbuffers::TaggedUnion>::Tag as flatbuffers::Follow<'a>>::Inner,
    pos: usize,
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    match tag {
      GameMessage::PlayerStatEvent => v
        .verify_union_variant::<flatbuffers::ForwardsUOffset<PlayerStatEvent>>(
          "GameMessage::PlayerStatEvent",
          pos,
        ),
      GameMessage::PlayerSpectate => v
        .verify_union_variant::<flatbuffers::ForwardsUOffset<PlayerSpectate>>(
          "GameMessage::PlayerSpectate",
          pos,
        ),
      GameMessage::PlayerInputChange => v
        .verify_union_variant::<flatbuffers::ForwardsUOffset<PlayerInputChange>>(
          "GameMessage::PlayerInputChange",
          pos,
        ),
      _ => Ok(()),
    }
  }
}

// struct PossiblyReservedWords, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct PossiblyReservedWords(pub [u8; 16]);
impl Default for PossiblyReservedWords { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for PossiblyReservedWords {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("PossiblyReservedWords")
      .field("follow_", &self.follow_())
      .field("push_", &self.push_())
      .field("size", &self.size())
      .field("alignment", &self.alignment())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for PossiblyReservedWords {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for PossiblyReservedWords {
  type Inner = &'a PossiblyReservedWords;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    unsafe { <&'a PossiblyReservedWords>::follow(buf, loc) }
  }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for &'a PossiblyReservedWords {
  type Inner = &'a PossiblyReservedWords;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    unsafe { flatbuffers::follow_cast_ref::<PossiblyReservedWords, B>(buf, loc) }
  }
}
impl<'b> flatbuffers::Push for PossiblyReservedWords {
    type Output = PossiblyReservedWords;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const PossiblyReservedWords as *const u8, <Self as flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> flatbuffers::Verifiable for PossiblyReservedWords {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> PossiblyReservedWords {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    follow_: f32,
    push_: f32,
    size: f32,
    alignment: f32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_follow_(follow_);
    s.set_push_(push_);
    s.set_size(size);
    s.set_alignment(alignment);
    s
  }

  pub fn follow_(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_follow_(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn push_(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_push_(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn size(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_size(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn alignment(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_alignment(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum FieldTableOffset {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Copy for FieldTable<'a, B> {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Clone for FieldTable<'a, B> {
  fn clone(&self) -> Self { *self }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized + PartialEq> PartialEq for FieldTable<'a, B> {
  fn eq(&self, other: &Self) -> bool { self._tab.eq(&other._tab) }
}

pub struct FieldTable<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for FieldTable<'a, B> {
  type Inner = FieldTable<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> FieldTable<'a, B> {

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    FieldTable { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args FieldTableArgs
  ) -> flatbuffers::WIPOffset<FieldTable<'bldr>> {
    let mut builder = FieldTableBuilder::new(_fbb);
    builder.finish()
  }

}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for FieldTable<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct FieldTableArgs {
}
impl<'a> Default for FieldTableArgs {
  #[inline]
  fn default() -> Self {
    FieldTableArgs {
    }
  }
}

pub struct FieldTableBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FieldTableBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FieldTableBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FieldTableBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FieldTable<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FieldTable<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FieldTable");
      ds.finish()
  }
}
pub enum RootTableOffset {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Copy for RootTable<'a, B> {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Clone for RootTable<'a, B> {
  fn clone(&self) -> Self { *self }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized + PartialEq> PartialEq for RootTable<'a, B> {
  fn eq(&self, other: &Self) -> bool { self._tab.eq(&other._tab) }
}

pub struct RootTable<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for RootTable<'a, B> {
  type Inner = RootTable<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> RootTable<'a, B> {
  pub const VT_FIELD42_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_FIELD42: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    RootTable { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RootTableArgs
  ) -> flatbuffers::WIPOffset<RootTable<'bldr>> {
    let mut builder = RootTableBuilder::new(_fbb);
    if let Some(x) = args.field42 { builder.add_field42(x); }
    builder.add_field42_type(args.field42_type);
    builder.finish()
  }


  #[inline]
  pub fn field42_type(&self) -> FieldUnion {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<FieldUnion>(RootTable::VT_FIELD42_TYPE, Some(FieldUnion::NONE)).unwrap()}
  }
  #[inline]
  pub fn field42(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(RootTable::VT_FIELD42, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn field42_as_f(&self) -> Option<FieldTable<'a>> {
    if self.field42_type() == FieldUnion::f {
      self.field42().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { FieldTable::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for RootTable<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<FieldUnionUnionValue>("field42_type", Self::VT_FIELD42_TYPE, "field42", Self::VT_FIELD42, false)?
     .finish();
    Ok(())
  }
}
pub struct RootTableArgs {
    pub field42_type: FieldUnion,
    pub field42: Option<flatbuffers::WIPOffset<FieldUnionUnionValue>>,
}
impl<'a> Default for RootTableArgs {
  #[inline]
  fn default() -> Self {
    RootTableArgs {
      field42_type: FieldUnion::NONE,
      field42: None,
    }
  }
}

pub struct RootTableBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RootTableBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_field42_type(&mut self, field42_type: FieldUnion) {
    self.fbb_.push_slot::<FieldUnion>(RootTable::VT_FIELD42_TYPE, field42_type, FieldUnion::NONE);
  }
  #[inline]
  pub fn add_field42(&mut self, field42: flatbuffers::WIPOffset<FieldUnionUnionValue>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RootTable::VT_FIELD42, field42);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RootTableBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RootTableBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RootTable<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RootTable<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RootTable");
      ds.field("field42_type", &self.field42_type());
      match self.field42_type() {
        FieldUnion::f => {
          if let Some(x) = self.field42_as_f() {
            ds.field("field42", &x)
          } else {
            ds.field("field42", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("field42", &x)
        },
      };
      ds.finish()
  }
}
pub enum PlayerStatEventOffset {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Copy for PlayerStatEvent<'a, B> {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Clone for PlayerStatEvent<'a, B> {
  fn clone(&self) -> Self { *self }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized + PartialEq> PartialEq for PlayerStatEvent<'a, B> {
  fn eq(&self, other: &Self) -> bool { self._tab.eq(&other._tab) }
}

pub struct PlayerStatEvent<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for PlayerStatEvent<'a, B> {
  type Inner = PlayerStatEvent<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> PlayerStatEvent<'a, B> {

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    PlayerStatEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args PlayerStatEventArgs
  ) -> flatbuffers::WIPOffset<PlayerStatEvent<'bldr>> {
    let mut builder = PlayerStatEventBuilder::new(_fbb);
    builder.finish()
  }

}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for PlayerStatEvent<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct PlayerStatEventArgs {
}
impl<'a> Default for PlayerStatEventArgs {
  #[inline]
  fn default() -> Self {
    PlayerStatEventArgs {
    }
  }
}

pub struct PlayerStatEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PlayerStatEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerStatEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PlayerStatEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerStatEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerStatEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerStatEvent");
      ds.finish()
  }
}
pub enum PlayerSpectateOffset {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Copy for PlayerSpectate<'a, B> {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Clone for PlayerSpectate<'a, B> {
  fn clone(&self) -> Self { *self }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized + PartialEq> PartialEq for PlayerSpectate<'a, B> {
  fn eq(&self, other: &Self) -> bool { self._tab.eq(&other._tab) }
}

pub struct PlayerSpectate<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for PlayerSpectate<'a, B> {
  type Inner = PlayerSpectate<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> PlayerSpectate<'a, B> {

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    PlayerSpectate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args PlayerSpectateArgs
  ) -> flatbuffers::WIPOffset<PlayerSpectate<'bldr>> {
    let mut builder = PlayerSpectateBuilder::new(_fbb);
    builder.finish()
  }

}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for PlayerSpectate<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct PlayerSpectateArgs {
}
impl<'a> Default for PlayerSpectateArgs {
  #[inline]
  fn default() -> Self {
    PlayerSpectateArgs {
    }
  }
}

pub struct PlayerSpectateBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PlayerSpectateBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerSpectateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PlayerSpectateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerSpectate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerSpectate<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerSpectate");
      ds.finish()
  }
}
pub enum PlayerInputChangeOffset {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Copy for PlayerInputChange<'a, B> {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Clone for PlayerInputChange<'a, B> {
  fn clone(&self) -> Self { *self }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized + PartialEq> PartialEq for PlayerInputChange<'a, B> {
  fn eq(&self, other: &Self) -> bool { self._tab.eq(&other._tab) }
}

pub struct PlayerInputChange<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for PlayerInputChange<'a, B> {
  type Inner = PlayerInputChange<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> PlayerInputChange<'a, B> {

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    PlayerInputChange { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args PlayerInputChangeArgs
  ) -> flatbuffers::WIPOffset<PlayerInputChange<'bldr>> {
    let mut builder = PlayerInputChangeBuilder::new(_fbb);
    builder.finish()
  }

}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for PlayerInputChange<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct PlayerInputChangeArgs {
}
impl<'a> Default for PlayerInputChangeArgs {
  #[inline]
  fn default() -> Self {
    PlayerInputChangeArgs {
    }
  }
}

pub struct PlayerInputChangeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PlayerInputChangeBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerInputChangeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PlayerInputChangeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerInputChange<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerInputChange<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerInputChange");
      ds.finish()
  }
}
pub enum GameMessageWrapperOffset {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Copy for GameMessageWrapper<'a, B> {}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> Clone for GameMessageWrapper<'a, B> {
  fn clone(&self) -> Self { *self }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized + PartialEq> PartialEq for GameMessageWrapper<'a, B> {
  fn eq(&self, other: &Self) -> bool { self._tab.eq(&other._tab) }
}

pub struct GameMessageWrapper<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for GameMessageWrapper<'a, B> {
  type Inner = GameMessageWrapper<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> GameMessageWrapper<'a, B> {
  pub const VT_MESSAGE_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_MESSAGE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    GameMessageWrapper { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GameMessageWrapperArgs
  ) -> flatbuffers::WIPOffset<GameMessageWrapper<'bldr>> {
    let mut builder = GameMessageWrapperBuilder::new(_fbb);
    if let Some(x) = args.Message { builder.add_Message(x); }
    builder.add_Message_type(args.Message_type);
    builder.finish()
  }


  #[inline]
  pub fn Message_type(&self) -> GameMessage {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<GameMessage>(GameMessageWrapper::VT_MESSAGE_TYPE, Some(GameMessage::NONE)).unwrap()}
  }
  #[inline]
  pub fn Message(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(GameMessageWrapper::VT_MESSAGE, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn Message_as_player_stat_event(&self) -> Option<PlayerStatEvent<'a>> {
    if self.Message_type() == GameMessage::PlayerStatEvent {
      self.Message().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PlayerStatEvent::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn Message_as_player_spectate(&self) -> Option<PlayerSpectate<'a>> {
    if self.Message_type() == GameMessage::PlayerSpectate {
      self.Message().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PlayerSpectate::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn Message_as_player_input_change(&self) -> Option<PlayerInputChange<'a>> {
    if self.Message_type() == GameMessage::PlayerInputChange {
      self.Message().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PlayerInputChange::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for GameMessageWrapper<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<GameMessageUnionValue>("Message_type", Self::VT_MESSAGE_TYPE, "Message", Self::VT_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct GameMessageWrapperArgs {
    pub Message_type: GameMessage,
    pub Message: Option<flatbuffers::WIPOffset<GameMessageUnionValue>>,
}
impl<'a> Default for GameMessageWrapperArgs {
  #[inline]
  fn default() -> Self {
    GameMessageWrapperArgs {
      Message_type: GameMessage::NONE,
      Message: None,
    }
  }
}

pub struct GameMessageWrapperBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GameMessageWrapperBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_Message_type(&mut self, Message_type: GameMessage) {
    self.fbb_.push_slot::<GameMessage>(GameMessageWrapper::VT_MESSAGE_TYPE, Message_type, GameMessage::NONE);
  }
  #[inline]
  pub fn add_Message(&mut self, Message: flatbuffers::WIPOffset<GameMessageUnionValue>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameMessageWrapper::VT_MESSAGE, Message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GameMessageWrapperBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GameMessageWrapperBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GameMessageWrapper<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GameMessageWrapper<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GameMessageWrapper");
      ds.field("Message_type", &self.Message_type());
      match self.Message_type() {
        GameMessage::PlayerStatEvent => {
          if let Some(x) = self.Message_as_player_stat_event() {
            ds.field("Message", &x)
          } else {
            ds.field("Message", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        GameMessage::PlayerSpectate => {
          if let Some(x) = self.Message_as_player_spectate() {
            ds.field("Message", &x)
          } else {
            ds.field("Message", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        GameMessage::PlayerInputChange => {
          if let Some(x) = self.Message_as_player_input_change() {
            ds.field("Message", &x)
          } else {
            ds.field("Message", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("Message", &x)
        },
      };
      ds.finish()
  }
}
}  // pub mod RustNamerTest

