// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FIELD_UNION: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FIELD_UNION: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FIELD_UNION: [FieldUnion; 2] = [
  FieldUnion::NONE,
  FieldUnion::f,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FieldUnion(pub u8);
#[allow(non_upper_case_globals)]
impl FieldUnion {
  pub const NONE: Self = Self(0);
  pub const f: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::f,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::f => Some("f"),
      _ => None,
    }
  }

  #[inline]
  pub fn tag_as_f(
    o: flatbuffers::WIPOffset<FieldTable>,
  ) -> flatbuffers::UnionWIPOffset<FieldUnionUnionValue> {
    flatbuffers::UnionWIPOffset::new(Self::f, flatbuffers::WIPOffset::new(o.value()))
  }

}
impl core::fmt::Debug for FieldUnion {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for FieldUnion {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<u8, B>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for FieldUnion {
    type Output = FieldUnion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for FieldUnion {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for FieldUnion {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for FieldUnion {}

impl From<FieldUnion> for u8 {
  #[inline]
  fn from(v: FieldUnion) -> u8 {
    v.0
  }
}

impl<'a: 'b, 'b> flatbuffers::BuildVector<'a, 'b> for FieldUnion {
  type VectorBuilder = FieldUnionVectorBuilder<'a, 'b>;
}

pub struct FieldUnionVectorBuilder<'a: 'b, 'b> {
  fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  num_items: usize,
}

impl<'a: 'b, 'b> FieldUnionVectorBuilder<'a, 'b> {
  #[inline]
  pub fn new(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, num_items: usize) -> Self {
    fbb.start_union_vector::<FieldUnionUnionValue>(num_items);
    Self { fbb, num_items }
  }

  #[inline]
  pub fn finish(&mut self) -> flatbuffers::UnionVectorWIPOffsets<'a, FieldUnionUnionValue> {
    self.fbb.end_union_vector(self.num_items)
  }

  #[inline]
  pub fn push_as_f(&mut self, o: flatbuffers::WIPOffset<FieldTable>) {
    self.fbb.push_union_vector_item(FieldUnion::tag_as_f(o));
  }

}

pub struct FieldUnionUnionValue {}

impl flatbuffers::TaggedUnion for FieldUnionUnionValue {
  type Tag = FieldUnion;
}

impl<'a> flatbuffers::UnionVerifiable<'a> for FieldUnionUnionValue {
  fn run_union_verifier(
    v: &mut flatbuffers::Verifier,
    tag: <<Self as flatbuffers::TaggedUnion>::Tag as flatbuffers::Follow<'a>>::Inner,
    pos: usize,
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    match tag {
      FieldUnion::f => v
        .verify_union_variant::<flatbuffers::ForwardsUOffset<FieldTable>>(
          "FieldUnion::f",
          pos,
        ),
      _ => Ok(()),
    }
  }
}

#[allow(clippy::upper_case_acronyms)]
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum FieldUnionT {
  NONE,
    F(Box<FieldTableT>),
}
impl Default for FieldUnionT {
  fn default() -> Self {
    Self::NONE
  }
}
impl FieldUnionT {
  pub fn field_union_type(&self) -> FieldUnion {
    match self {
      Self::NONE => FieldUnion::NONE,
      Self::F(_) => FieldUnion::f,
    }
  }
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(&self, fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>) -> Option<flatbuffers::WIPOffset<FieldUnionUnionValue>> {
    match self {
      Self::NONE => None,
        Self::F(v) => Some(FieldUnion::tag_as_f(v.pack(fbb)).value_offset()),
    }
  }
  /// If the union variant matches, return the owned FieldTableT, setting the union to NONE.
  pub fn take_f(&mut self) -> Option<Box<FieldTableT>> {
    if let Self::F(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::F(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the FieldTableT.
  pub fn as_f(&self) -> Option<&FieldTableT> {
    if let Self::F(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the FieldTableT.
  pub fn as_f_mut(&mut self) -> Option<&mut FieldTableT> {
    if let Self::F(v) = self { Some(v.as_mut()) } else { None }
  }
}
