// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum PlayerInputChangeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PlayerInputChange<'a, B: flatbuffers::ReadBuffer + ?Sized = [u8]> {
  pub _tab: flatbuffers::Table<'a, B>,
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Follow<'a, B> for PlayerInputChange<'a, B> {
  type Inner = PlayerInputChange<'a, B>;
  #[inline]
  unsafe fn follow(buf: &'a B, loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a, B: flatbuffers::ReadBuffer + ?Sized> PlayerInputChange<'a, B> {

  pub const fn get_fully_qualified_name() -> &'static str {
    "RustNamerTest.PlayerInputChange"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a, B>) -> Self {
    PlayerInputChange { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args PlayerInputChangeArgs
  ) -> flatbuffers::WIPOffset<PlayerInputChange<'bldr>> {
    let mut builder = PlayerInputChangeBuilder::new(_fbb);
    builder.finish()
  }

  pub fn unpack(&self) -> PlayerInputChangeT {
    PlayerInputChangeT {
    }
  }
}

impl<B: flatbuffers::ReadBuffer + ?Sized> flatbuffers::Verifiable for PlayerInputChange<'_, B> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct PlayerInputChangeArgs {
}
impl<'a> Default for PlayerInputChangeArgs {
  #[inline]
  fn default() -> Self {
    PlayerInputChangeArgs {
    }
  }
}

pub struct PlayerInputChangeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PlayerInputChangeBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PlayerInputChangeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PlayerInputChangeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PlayerInputChange<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PlayerInputChange<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PlayerInputChange");
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct PlayerInputChangeT {
}
impl Default for PlayerInputChangeT {
  fn default() -> Self {
    Self {
    }
  }
}
impl PlayerInputChangeT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<PlayerInputChange<'b>> {
    PlayerInputChange::create(_fbb, &PlayerInputChangeArgs{
    })
  }
}
